project:
  type: book
  output-dir: docs

book:
  title: "GSB 544: Data Science and Machine Learning with Python"
  author: "Kelly Bodwin and Hunter Glanz"
  date: "Sept 1, 2023"
  chapters:  
  - index.qmd
  - part: "Data Science with Python"
    chapters: 
    - 00-setup.qmd
    - 01-basics.qmd
    - 02-plotnine.qmd
    - 03-basic_data_operations.qmd
    - 04-pivoting_joining.qmd
    - 05-function_writing.qmd
    - 06-iteration.qmd
    - 07-webscraping.qmd
    - 08-regex.qmd
  - part: "Machine Learning with Python"
    chapters:
    - 09-modeling_intro.qmd
  site-url: https://DS-ML-with-python.github.io/Course-Textbook/
  repo-url: https://github.com/DS-ML-with-python/Course-Textbook/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  # toc:
    # collapse: section

bibliography: references.bib

engine: knitr

#pdf-engine: context

from: markdown+emoji

format:
  html:
    css: style.css
    # theme: cosmo
    code-link: true
    theme:
      light: [flatly, custom-callouts.scss]
      dark: [darkly, custom-callouts.scss]
    code-copy: true
    code-annotations: below
    
execute: 
  echo: true
  warning: false
  error: true
  freeze: auto
  
self-contained: true

  # pdf:
  #   documentclass: scrreport
  #epub:
  #  cover-image: cover.png

editor: source

