# Preface {.unnumbered}

This text was created for the Cal Poly course "GSB 544: Data Science and Machine Learning with Python" by [Dr. Kelly Bodwin](https://github.com/kbodwin) and [Dr. Hunter Glanz](https://github.com/hglanz). Some parts of the material and text are borrowed from [Dr. Emily Robinson's R course](https://earobinson95.github.io/stat331-calpoly-text/) and [Dr. Dennis Sun's python course](https://github.com/dlsun/pods)

This text is not meant to be a complete course or textbook by itself; rather, think of it as "long-form" class slides.  We will summarize the main concepts in each chapter, show you examples, point you to more in-depth readings from outside sources, and ask you to try out short tasks in python as you go.

## How to Use This Text


:::{.callout-tweet .icon}

Watch out sections contain things you may want to look out for - common errors, etc.
:::

:::{.callout-example .icon}

Example sections contain code and other information. Don't skip them!
:::

:::{.callout-required-reading .icon}

Consider these sections to be required readings/viewings.  This is where we will direct you to existing materials to explain or indroduce a concept. 

:::


:::{.callout-required-video .icon}

Consider these sections to be required readings/viewings.  This is where we will direct you to existing materials to explain or indroduce a concept. 

:::

:::{.callout-check-in .icon}

Check-in sections contain quizzes or preview activities to help you process the material. Although they are not graded, please treat them as required!
:::

:::{.callout-practice-exercise .icon}

Activities
:::

:::{.callout-learn-more .icon}

Consider these to be optional readings/viewings. The world of python programming has so many interesting tidbits, we can't possibly teach them all - but we want to share them with you nonetheless!
:::

:::{.callout-opinion .icon}

These are personal opinion comments from the authors.  Take them with a grain of salt; we aren't the only python programmers worth listening to, we are just sharing what has worked for us.

:::

:::{.callout-note}

Note sections contain clarification points (anywhere I would normally say "note that ....).  Make sure to read them to avoid any common pitfalls or misconceptions.
:::


## Additional Resources

References or additional readings may come from the following texts:

-   [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas
-   [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney
-   [Principles of Data Science](https://github.com/dlsun/pods) by Dennis Sun
 

For extra practice with python programming, we recommend the [DataQuest interactive tutorials](https://www.dataquest.io/course/introduction-to-python/) or working through some lessons on [Python for Everybody](https://www.py4e.com/).
